//! Packaged binary assets served through `asset://` sources.
//!
//! `provider_logo` is generated by `build.rs` from `assets/login/*.png`:
//! adding a PNG to that directory embeds and serves it with no code change.
//! [`crate::imagereg`] resolves `asset://login/<id>` sources through it.

include!(concat!(env!("OUT_DIR"), "/provider_logos.rs"));
