from _typeshed import Incomplete
from collections.abc import Sequence
from typing import Any, Final, final

@final
class ActivateReason:
    """
    Canonical Python ActivateReason vocabulary.
    """
    FIRST_REACH: Final[ActivateReason]
    HOT_RELOAD: Final[ActivateReason]
    RESTART: Final[ActivateReason]
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @property
    def value(self, /) -> str: ...

@final
class AgentUrl:
    """
    Typed Python AgentUrl URL value.
    """
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, value: str) -> AgentUrl: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    def read(self, /) -> Any: ...
    @property
    def resource(self, /) -> str: ...
    @property
    def selector(self, /) -> str |None: ...
    @property
    def uri(self, /) -> str: ...
    def with_selector(self, /, selector: str) -> AgentUrl: ...

@final
class ArtifactUrl:
    """
    Typed Python ArtifactUrl URL value.
    """
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, value: str) -> ArtifactUrl: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    def read(self, /) -> Any: ...
    @property
    def resource(self, /) -> str: ...
    @property
    def selector(self, /) -> str |None: ...
    @property
    def uri(self, /) -> str: ...
    def with_selector(self, /, selector: str) -> ArtifactUrl: ...

@final
class Authority:
    """
    Canonical Python Authority vocabulary.
    """
    CORE: Final[Authority]
    ENVIRONMENT: Final[Authority]
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @property
    def value(self, /) -> str: ...

@final
class BlobRef:
    """
    A content-addressed reference in one Environment blob store.
    """
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, hash: bytes, size: int) -> BlobRef: ...
    def __repr__(self, /) -> str: ...
    @property
    def hash(self, /) -> bytes: ...
    @property
    def hex(self, /) -> str: ...
    @property
    def size(self, /) -> int: ...

@final
class BlobStat:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, present: Any, size: Any) -> BlobStat: ...
    def __repr__(self, /) -> str: ...
    @property
    def present(self, /) -> Any: ...
    @property
    def size(self, /) -> Any: ...

@final
class Cancellation:
    """
    Frozen cancellation token shared safely by free-threaded Python callers.
    """
    def __new__(cls, /) -> Cancellation: ...
    def cancel(self, /) -> None: ...
    @property
    def cancelled(self, /) -> bool: ...

@final
class ClientPath:
    """
    A path in the client-machine filesystem namespace.
    """
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, value: str) -> ClientPath: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    def join(self, /, *parts) -> ClientPath: ...
    @property
    def uri(self, /) -> str: ...

@final
class Completed:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, outcome: Any, exit_code: Any, signal: Any, wall: Any, output: Any, artifact: Any, aborted: Any) -> Completed: ...
    def __repr__(self, /) -> str: ...
    @property
    def aborted(self, /) -> Any: ...
    @property
    def artifact(self, /) -> Any: ...
    @property
    def exit_code(self, /) -> Any: ...
    @property
    def outcome(self, /) -> Any: ...
    @property
    def output(self, /) -> Any: ...
    @property
    def signal(self, /) -> Any: ...
    def text(self, /, _channel: Any |None = None) -> str: ...
    @property
    def wall(self, /) -> Any: ...

@final
class ControlHandle:
    """
    Immutable reference to the inherited CONTROL transport.
    """
    def __new__(cls, /, fd: int) -> ControlHandle: ...
    @property
    def fd(self, /) -> int: ...

@final
class CopyResult:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, meta: Any, bytes_copied: Any) -> CopyResult: ...
    def __repr__(self, /) -> str: ...
    @property
    def bytes_copied(self, /) -> Any: ...
    @property
    def meta(self, /) -> Any: ...

@final
class CostClass:
    """
    Canonical Python CostClass vocabulary.
    """
    METERED: Final[CostClass]
    NONE: Final[CostClass]
    PAID: Final[CostClass]
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @property
    def value(self, /) -> str: ...

@final
class DirEntry:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, name: Any, meta: Any) -> DirEntry: ...
    def __repr__(self, /) -> str: ...
    @property
    def meta(self, /) -> Any: ...
    @property
    def name(self, /) -> Any: ...

@final
class DocEvent:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, sequence: Any, kind: Any, revision: Any, previous_revision: Any, txn_id: Any, invalidated_txn_ids: Any, previous_path: Any) -> DocEvent: ...
    def __repr__(self, /) -> str: ...
    @property
    def invalidated_txn_ids(self, /) -> Any: ...
    @property
    def kind(self, /) -> Any: ...
    @property
    def previous_path(self, /) -> Any: ...
    @property
    def previous_revision(self, /) -> Any: ...
    @property
    def revision(self, /) -> Any: ...
    @property
    def sequence(self, /) -> Any: ...
    @property
    def txn_id(self, /) -> Any: ...

@final
class Durability:
    """
    Canonical Python Durability vocabulary.
    """
    DURABLE: Final[Durability]
    EPHEMERAL: Final[Durability]
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @property
    def value(self, /) -> str: ...

@final
class Duration:
    """
    Immutable Python duration retaining its explicit source unit.
    """
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, value: Any |None = None, *, seconds: float |None = None) -> Duration: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    def __sub__(self, other: object, /) -> Duration: ...
    @property
    def seconds(self, /) -> float: ...
    @property
    def unit(self, /) -> str: ...
    @property
    def value(self, /) -> int: ...

@final
class Entry:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, path: Any, kind: Any, size: Any, mtime_ms: Any, depth: Any) -> Entry: ...
    def __repr__(self, /) -> str: ...
    @property
    def depth(self, /) -> Any: ...
    @property
    def kind(self, /) -> Any: ...
    @property
    def mtime_ms(self, /) -> Any: ...
    @property
    def path(self, /) -> Any: ...
    @property
    def size(self, /) -> Any: ...

@final
class EnvInfo:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, workspace_id: Any, root: Any, server_epoch: Any, server_version: Any, server_build: Any, schema_rev: Any, capabilities: Any, remote: Any) -> EnvInfo: ...
    def __repr__(self, /) -> str: ...
    @property
    def capabilities(self, /) -> Any: ...
    @property
    def remote(self, /) -> Any: ...
    @property
    def root(self, /) -> Any: ...
    @property
    def schema_rev(self, /) -> Any: ...
    @property
    def server_build(self, /) -> Any: ...
    @property
    def server_epoch(self, /) -> Any: ...
    @property
    def server_version(self, /) -> Any: ...
    @property
    def workspace_id(self, /) -> Any: ...

@final
class EnvPath:
    """
    A path in the workspace Environment filesystem namespace.
    """
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, value: str) -> EnvPath: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    def join(self, /, *parts) -> EnvPath: ...
    def local_path(self, /) -> Any: ...
    def read_bytes(self, /) -> Any: ...
    def read_text(self, /, encoding: str = "utf-8") -> Any: ...
    @property
    def uri(self, /) -> str: ...

@final
class Exit:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, status: Any) -> Exit: ...
    def __repr__(self, /) -> str: ...
    @property
    def status(self, /) -> Any: ...

@final
class HistoryUrl:
    """
    Typed Python HistoryUrl URL value.
    """
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, value: str) -> HistoryUrl: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    def read(self, /) -> Any: ...
    @property
    def resource(self, /) -> str: ...
    @property
    def selector(self, /) -> str |None: ...
    @property
    def uri(self, /) -> str: ...
    def with_selector(self, /, selector: str) -> HistoryUrl: ...

@final
class HttpResponse:
    def __new__(cls, /, status: Any, headers: Any, body: Any, final_url: Any) -> HttpResponse: ...
    def __repr__(self, /) -> str: ...
    @property
    def body(self, /) -> Any: ...
    @property
    def final_url(self, /) -> Any: ...
    @property
    def headers(self, /) -> Any: ...
    def json(self, /) -> Any: ...
    @property
    def status(self, /) -> Any: ...

@final
class InvocationPhase:
    """
    Canonical ordered Python invocation phase.
    """
    ADMISSION: Final[InvocationPhase]
    ADMITTED: Final[InvocationPhase]
    ARGS_FINALIZED: Final[InvocationPhase]
    ASSISTANT_ITEM_COMMITTED: Final[InvocationPhase]
    EFFECTS_AUTHORIZED: Final[InvocationPhase]
    OPEN: Final[InvocationPhase]
    SETTLED: Final[InvocationPhase]
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @property
    def ordinal(self, /) -> int: ...
    @property
    def value(self, /) -> str: ...

@final
class LifecyclePhase:
    """
    Canonical ordered Python extension lifecycle phase.
    """
    ACTIVE: Final[LifecyclePhase]
    DECLARED: Final[LifecyclePhase]
    DEGRADED: Final[LifecyclePhase]
    FROZEN: Final[LifecyclePhase]
    VERIFIED: Final[LifecyclePhase]
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @property
    def ordinal(self, /) -> int: ...
    @property
    def value(self, /) -> str: ...

@final
class LspBinding:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, server_id: Any, name: Any, sync: Any, capabilities: Any) -> LspBinding: ...
    def __repr__(self, /) -> str: ...
    @property
    def capabilities(self, /) -> Any: ...
    @property
    def name(self, /) -> Any: ...
    @property
    def server_id(self, /) -> Any: ...
    @property
    def sync(self, /) -> Any: ...

@final
class LspBindingEvent:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, kind: Any, binding: Any, path: Any) -> LspBindingEvent: ...
    def __repr__(self, /) -> str: ...
    @property
    def binding(self, /) -> Any: ...
    @property
    def kind(self, /) -> Any: ...
    @property
    def path(self, /) -> Any: ...

@final
class LspError:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, code: Any, message: Any, data: Any) -> LspError: ...
    def __repr__(self, /) -> str: ...
    @property
    def code(self, /) -> Any: ...
    @property
    def data(self, /) -> Any: ...
    @property
    def message(self, /) -> Any: ...

@final
class LspEvent:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, server_id: Any, method: Any, params: Any, path: Any, revision: Any) -> LspEvent: ...
    def __repr__(self, /) -> str: ...
    @property
    def method(self, /) -> Any: ...
    @property
    def params(self, /) -> Any: ...
    @property
    def path(self, /) -> Any: ...
    @property
    def revision(self, /) -> Any: ...
    @property
    def server_id(self, /) -> Any: ...

@final
class LspReply:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, revision: Any, result: Any, error: Any) -> LspReply: ...
    def __repr__(self, /) -> str: ...
    @property
    def error(self, /) -> Any: ...
    @property
    def result(self, /) -> Any: ...
    @property
    def revision(self, /) -> Any: ...

@final
class Match:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, path: Any, line: Any, byte_offset: Any, line_bytes: Any) -> Match: ...
    def __repr__(self, /) -> str: ...
    @property
    def byte_offset(self, /) -> Any: ...
    @property
    def line(self, /) -> Any: ...
    @property
    def line_bytes(self, /) -> Any: ...
    @property
    def path(self, /) -> Any: ...

@final
class OpenedDoc:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, lease: Any, revision: Any) -> OpenedDoc: ...
    def __repr__(self, /) -> str: ...
    @property
    def lease(self, /) -> Any: ...
    @property
    def revision(self, /) -> Any: ...

@final
class OpenedSession:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, id: Any, cwd: Any) -> OpenedSession: ...
    def __repr__(self, /) -> str: ...
    @property
    def cwd(self, /) -> Any: ...
    @property
    def id(self, /) -> Any: ...

@final
class OperationSpec:
    """
    Generated phase, durability, cost, and authority metadata.
    """
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    @property
    def authority(self, /) -> Authority: ...
    @property
    def cost(self, /) -> CostClass: ...
    @property
    def durability(self, /) -> Durability: ...
    @property
    def minimum_phase(self, /) -> InvocationPhase: ...

@final
class Output:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, channel: Any, data: Any, sequence: Any) -> Output: ...
    def __repr__(self, /) -> str: ...
    @property
    def channel(self, /) -> Any: ...
    @property
    def data(self, /) -> Any: ...
    @property
    def sequence(self, /) -> Any: ...

@final
class PathMeta:
    def __new__(cls, /, path: EnvPath, kind: Any, byte_length: int, read_only: bool |None = None, executable: bool |None = None, modified: float |None = None, accessed: float |None = None, created: float |None = None) -> PathMeta: ...
    def __repr__(self, /) -> str: ...
    @property
    def accessed(self, /) -> float |None: ...
    @property
    def byte_length(self, /) -> int: ...
    @property
    def created(self, /) -> float |None: ...
    @property
    def executable(self, /) -> bool |None: ...
    @property
    def kind(self, /) -> Any: ...
    @property
    def modified(self, /) -> float |None: ...
    @property
    def path(self, /) -> EnvPath: ...
    @property
    def read_only(self, /) -> bool |None: ...

@final
class Principal:
    """
    Core-authenticated principal identity exposed read-only to Python.
    """
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    @staticmethod
    def __repr__() -> str: ...
    @property
    def display(self, /) -> str: ...
    @property
    def id(self, /) -> str: ...

@final
class ProcessInfo:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, name: Any, generation: Any, state: Any, status: Any) -> ProcessInfo: ...
    def __repr__(self, /) -> str: ...
    @property
    def generation(self, /) -> Any: ...
    @property
    def name(self, /) -> Any: ...
    @property
    def state(self, /) -> Any: ...
    @property
    def status(self, /) -> Any: ...

@final
class ProcessOutput:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, generation: Any, channel: Any, data: Any, sequence: Any) -> ProcessOutput: ...
    def __repr__(self, /) -> str: ...
    @property
    def channel(self, /) -> Any: ...
    @property
    def data(self, /) -> Any: ...
    @property
    def generation(self, /) -> Any: ...
    @property
    def sequence(self, /) -> Any: ...

@final
class PyBlobUpload: ...

@final
class PyEnvironmentBackend:
    def abort_blob(self, /, upload: PyBlobUpload) -> None: ...
    def blob_commit(self, /, *args, **kwargs) -> Any: ...
    def blob_write(self, /, *args, **kwargs) -> Any: ...
    def blob_writer(self, /) -> Any: ...
    def blobs_delete(self, /, *args, **kwargs) -> Any: ...
    def blobs_get(self, /, *args, **kwargs) -> Any: ...
    def blobs_put_bytes(self, /, *args, **kwargs) -> Any: ...
    def blobs_put_path(self, /, *args, **kwargs) -> Any: ...
    def blobs_stat(self, /, *args, **kwargs) -> Any: ...
    def blobs_stream(self, /, *args, **kwargs) -> Any: ...
    def cancel_run(self, /, run_id: bytes) -> None: ...
    def doc_close(self, /, *args, **kwargs) -> Any: ...
    def doc_edit(self, /, *args, **kwargs) -> Any: ...
    def doc_events(self, /, *args, **kwargs) -> Any: ...
    def doc_hashline(self, /, *args, **kwargs) -> Any: ...
    def doc_lines(self, /, *args, **kwargs) -> Any: ...
    def doc_read_bytes(self, /, *args, **kwargs) -> Any: ...
    def doc_refresh(self, /, *args, **kwargs) -> Any: ...
    def doc_summary(self, /, *args, **kwargs) -> Any: ...
    def doc_write(self, /, *args, **kwargs) -> Any: ...
    def docs_open(self, /, *args, **kwargs) -> Any: ...
    def docs_read_bytes(self, /, *args, **kwargs) -> Any: ...
    def find_files(self, /, *args, **kwargs) -> Any: ...
    def find_search(self, /, *args, **kwargs) -> Any: ...
    def find_walk(self, /, *args, **kwargs) -> Any: ...
    def fs_canonicalize(self, /, *args, **kwargs) -> Any: ...
    def fs_chmod(self, /, *args, **kwargs) -> Any: ...
    def fs_copy(self, /, *args, **kwargs) -> Any: ...
    def fs_hard_link(self, /, *args, **kwargs) -> Any: ...
    def fs_list_dir(self, /, *args, **kwargs) -> Any: ...
    def fs_lstat(self, /, *args, **kwargs) -> Any: ...
    def fs_mkdir(self, /, *args, **kwargs) -> Any: ...
    def fs_read_link(self, /, *args, **kwargs) -> Any: ...
    def fs_remove(self, /, *args, **kwargs) -> Any: ...
    def fs_rename(self, /, *args, **kwargs) -> Any: ...
    def fs_stat(self, /, *args, **kwargs) -> Any: ...
    def fs_symlink(self, /, *args, **kwargs) -> Any: ...
    def http_request(self, /, *args, **kwargs) -> Any: ...
    def lsp_bindings(self, /, *args, **kwargs) -> Any: ...
    def lsp_events(self, /, *args, **kwargs) -> Any: ...
    def lsp_notify(self, /, *args, **kwargs) -> Any: ...
    def lsp_request(self, /, *args, **kwargs) -> Any: ...
    def parse_script(self, /, _script: str) -> Any: ...
    def proc_adopt(self, /, *args, **kwargs) -> Any: ...
    def proc_ensure(self, /, *args, **kwargs) -> Any: ...
    def proc_list(self, /, *args, **kwargs) -> Any: ...
    def proc_start(self, /, *args, **kwargs) -> Any: ...
    def process_endpoint(self, /, name: str, generation: int) -> str |None: ...
    def process_eof(self, /, *args, **kwargs) -> Any: ...
    def process_info(self, /, *args, **kwargs) -> Any: ...
    def process_output(self, /, *args, **kwargs) -> Any: ...
    def process_restart(self, /, *args, **kwargs) -> Any: ...
    def process_send(self, /, *args, **kwargs) -> Any: ...
    def process_signal(self, /, *args, **kwargs) -> Any: ...
    def process_states(self, /, *args, **kwargs) -> Any: ...
    def process_stop(self, /, *args, **kwargs) -> Any: ...
    def request(self, /, operation: str, arguments: dict) -> Any: ...
    def run_detach(self, /, *args, **kwargs) -> Any: ...
    def run_eof(self, /, *args, **kwargs) -> Any: ...
    def run_events(self, /, *args, **kwargs) -> Any: ...
    def run_resize(self, /, *args, **kwargs) -> Any: ...
    def run_signal(self, /, *args, **kwargs) -> Any: ...
    def run_stdin(self, /, *args, **kwargs) -> Any: ...
    def run_wait(self, /, *args, **kwargs) -> Any: ...
    def session(self, /, arguments: dict) -> Any: ...
    def session_close(self, /, *args, **kwargs) -> Any: ...
    def session_open(self, /, *args, **kwargs) -> Any: ...
    def session_run(self, /, *args, **kwargs) -> Any: ...
    def stream(self, /, operation: str, arguments: dict) -> Any: ...
    def txn_commit(self, /, *args, **kwargs) -> Any: ...
    def worktree(self, /, *args, **kwargs) -> Any: ...

@final
class PyEnvironmentStream:
    def __iter__(self, /) -> PyEnvironmentStream: ...
    def __next__(self, /) -> Any |None: ...
    def close(self, /) -> None: ...

@final
class PySecretUse:
    """
    Short-lived Python context manager for a [`PySecret`] exposure.
    """
    def __enter__(self, /) -> bytes: ...
    def __exit__(self, /, _exc_type: Any |None, _exc_value: Any |None, _traceback: Any |None) -> bool: ...

@final
class QuotaStatus:
    """
    One quota's immutable local standing.
    """
    @property
    def limit(self, /) -> int: ...
    @property
    def used(self, /) -> int: ...
    @property
    def window(self, /) -> Duration |None: ...

@final
class ResourceReceipt:
    """
    Immutable snapshot of extension resource quota standing.
    """
    @property
    def dropped(self, /) -> Any: ...
    @property
    def quotas(self, /) -> Any: ...

@final
class RestartReason:
    """
    Canonical Python RestartReason vocabulary.
    """
    CANCEL_ESCALATION: Final[RestartReason]
    CRASH: Final[RestartReason]
    HEALTH_TIMEOUT: Final[RestartReason]
    HOT_RELOAD: Final[RestartReason]
    OOM: Final[RestartReason]
    PROTOCOL_ERROR: Final[RestartReason]
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @property
    def value(self, /) -> str: ...

@final
class Revision:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, sequence: int, content_hash: Sequence[int]) -> Revision: ...
    def __repr__(self, /) -> str: ...
    @property
    def content_hash(self, /) -> bytes: ...
    @property
    def hex(self, /) -> str: ...
    @property
    def sequence(self, /) -> int: ...

@final
class Secret:
    """
    Opaque Python secret whose representation never reveals its bytes.

    Raw bytes are available only from the temporary value yielded by
    [`Self::use_`]; callers must use that context manager rather than logging
    this object.
    """
    def __format__(self, /, _format_spec: str) -> str: ...
    def __new__(cls, /, bytes: bytes) -> Secret: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    def use(self, /) -> PySecretUse:
        """
        Returns a context manager which temporarily yields the secret bytes.
        """

@final
class StartedProcess:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, name: Any, generation: Any, endpoint: Any) -> StartedProcess: ...
    def __repr__(self, /) -> str: ...
    @property
    def endpoint(self, /) -> Any: ...
    @property
    def generation(self, /) -> Any: ...
    @property
    def name(self, /) -> Any: ...

@final
class StartedRun:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, id: Any) -> StartedRun: ...
    def __repr__(self, /) -> str: ...
    @property
    def id(self, /) -> Any: ...

@final
class StateScope:
    """
    Canonical Python StateScope vocabulary.
    """
    ORGANIZATION: Final[StateScope]
    PROJECT: Final[StateScope]
    SESSION: Final[StateScope]
    USER: Final[StateScope]
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @property
    def value(self, /) -> str: ...

@final
class Summary:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, language: Any, parsed: Any, elided: Any, total_lines: Any, segments: Any, text: Any, display_text: Any, elided_ranges: Any, elided_lines: Any) -> Summary: ...
    def __repr__(self, /) -> str: ...
    @property
    def display_text(self, /) -> Any: ...
    @property
    def elided(self, /) -> Any: ...
    @property
    def elided_lines(self, /) -> Any: ...
    @property
    def elided_ranges(self, /) -> Any: ...
    @property
    def language(self, /) -> Any: ...
    @property
    def parsed(self, /) -> Any: ...
    @property
    def segments(self, /) -> Any: ...
    @property
    def text(self, /) -> Any: ...
    @property
    def total_lines(self, /) -> Any: ...

@final
class SummarySegment:
    def __new__(cls, /, kept: bool, start_line: int, end_line: int, text: str |None) -> SummarySegment: ...
    def __repr__(self, /) -> str: ...
    @property
    def end_line(self, /) -> int: ...
    @property
    def kept(self, /) -> bool: ...
    @property
    def start_line(self, /) -> int: ...
    @property
    def text(self, /) -> str |None: ...

@final
class SummaryUnavailable:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, reason: Any, total_lines: Any, language: Any, parsed: Any) -> SummaryUnavailable: ...
    def __repr__(self, /) -> str: ...
    @property
    def language(self, /) -> Any: ...
    @property
    def parsed(self, /) -> Any: ...
    @property
    def reason(self, /) -> Any: ...
    @property
    def total_lines(self, /) -> Any: ...

@final
class SymlinkTarget:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, target: Any, relative: Any) -> SymlinkTarget: ...
    def __repr__(self, /) -> str: ...
    @property
    def relative(self, /) -> Any: ...
    @property
    def target(self, /) -> Any: ...

@final
class SyncPolicy:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, change: Any, open_close: Any, will_save: Any, will_save_wait_until: Any, save: Any, save_include_text: Any, position_encoding: Any) -> SyncPolicy: ...
    def __repr__(self, /) -> str: ...
    @property
    def change(self, /) -> Any: ...
    @property
    def open_close(self, /) -> Any: ...
    @property
    def position_encoding(self, /) -> Any: ...
    @property
    def save(self, /) -> Any: ...
    @property
    def save_include_text(self, /) -> Any: ...
    @property
    def will_save(self, /) -> Any: ...
    @property
    def will_save_wait_until(self, /) -> Any: ...

@final
class Template:
    """
    Compiled, immutable scribe template rendering against the shared
    builtin engine. Rendering is pure: output depends only on the source
    and the props.
    """
    def __new__(cls, /, source: str, *, name: str = "template") -> Template: ...
    def __repr__(self, /) -> str: ...
    @property
    def name(self, /) -> str:
        """
        The name supplied at compile time (used in error messages).
        """
    @property
    def referenced_keys(self, /) -> tuple:
        """
        Sorted, deduplicated top-level prop names the template reads.
        """
    def render(self, /, props: dict |None = None) -> str:
        """
        Renders the template with `props` (a `dict` with string keys).
        """

@final
class TxnOutcome:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, txn_id: Any, committed: Any, operation_count: Any) -> TxnOutcome: ...
    def __repr__(self, /) -> str: ...
    @property
    def committed(self, /) -> Any: ...
    @property
    def operation_count(self, /) -> Any: ...
    @property
    def txn_id(self, /) -> Any: ...

@final
class TxnReceipt:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, txn_id: Any, revision: Any, rebased: Any, formatted: Any) -> TxnReceipt: ...
    def __repr__(self, /) -> str: ...
    @property
    def formatted(self, /) -> Any: ...
    @property
    def rebased(self, /) -> Any: ...
    @property
    def revision(self, /) -> Any: ...
    @property
    def txn_id(self, /) -> Any: ...

@final
class WorkspaceUri:
    """
    Typed Python WorkspaceUri location value.
    """
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, value: str) -> WorkspaceUri: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    @property
    def uri(self, /) -> str: ...

@final
class WorktreeInfo:
    def __eq__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __gt__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __new__(cls, /, id: Any, root: Any, base: Any, generation: Any) -> WorktreeInfo: ...
    def __repr__(self, /) -> str: ...
    @property
    def base(self, /) -> Any: ...
    @property
    def generation(self, /) -> Any: ...
    @property
    def id(self, /) -> Any: ...
    @property
    def root(self, /) -> Any: ...

def _interrupt(thread_id: int) -> bool:
    """
    Deliver a stage-two `KeyboardInterrupt` to a Python thread id.
    """

def _local_path_string(_path: EnvPath) -> str: ...
def _open_environment_scope(socket: str, invocation: str, effect_token: bytes, host_generation: int, session_generation: int, pty_denied: bool) -> tuple[PyEnvironmentBackend, Any]: ...
def _phase_legality_matrix() -> Any: ...
def _principal_from_host(id: str, display: str) -> Principal: ...
def _runtime_metadata() -> Any: ...
def _scheme_snapshot() -> Any: ...

def _scribe_canonicalize(text: str) -> str:
    """
    Canonicalizes rendered prompt text: strips HTML comments, collapses
    blank runs, compacts GFM table separators, and aliases RFC 2119
    phrasing, all outside code fences and inline code spans.
    """

def _thread_id() -> int:
    """
    Return `CPython`'s identifier for the attached current thread.
    """

def operation_spec(symbol: Any) -> OperationSpec |None: ...
def resources() -> ResourceReceipt: ...
def __getattr__(name: str) -> Incomplete: ...
