//! Closed compatibility-directive vocabulary.

use strum::{Display, EnumString, IntoStaticStr};

/// Namespace owning a compatibility axis.
#[derive(Clone, Copy, Debug, Display, EnumString, Eq, IntoStaticStr, PartialEq)]
#[strum(serialize_all = "kebab-case")]
pub enum AxisSet {
	/// Request-wire compatibility.
	Wire,
	/// Thinking-control compatibility.
	Thinking,
	/// Catalog metadata correction.
	Catalog,
}

/// KDL value shape accepted by an axis.
#[derive(Clone, Copy, Debug, Display, EnumString, Eq, IntoStaticStr, PartialEq)]
#[strum(serialize_all = "kebab-case")]
pub enum AxisShape {
	/// Exactly one scalar argument.
	Scalar,
	/// One or more scalar arguments.
	Array,
	/// A child object and no arguments.
	Object,
}

/// Typed resolved wire-policy record family.
#[derive(Clone, Copy, Debug, Display, EnumString, Eq, IntoStaticStr, PartialEq)]
#[strum(serialize_all = "kebab-case")]
pub enum CompatRecord {
	/// `OpenAI` chat completions.
	OpenAi,
	/// `OpenAI` Responses.
	OpenAiResponses,
	/// Anthropic Messages.
	Anthropic,
	/// Bedrock Converse Stream.
	Bedrock,
	/// Devin agent transport.
	Devin,
	/// Google APIs.
	Google,
}

/// One accepted compatibility directive.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct AxisDef {
	/// Kebab-case KDL directive spelling.
	pub key:           &'static str,
	/// Snake-case resolved Rust record field.
	pub resolved_key:  &'static str,
	/// Owning namespace.
	pub set:           AxisSet,
	/// Accepted KDL value shape.
	pub shape:         AxisShape,
	/// Wire record families carrying this field.
	pub records:       &'static [CompatRecord],
	/// Closed string vocabulary, or empty when the scalar type is unrestricted.
	pub values:        &'static [&'static str],
	/// Whether object child keys are copied verbatim instead of normalized.
	pub verbatim_keys: bool,
}

/// Complete sorted compatibility-directive vocabulary.
pub const AXES: &[AxisDef] = &[
	AxisDef {
		key:           "allow-anthropic-header-overrides",
		resolved_key:  "allow_anthropic_header_overrides",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Anthropic],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "allows-synthetic-reasoning-content-for-tool-calls",
		resolved_key:  "allows_synthetic_reasoning_content_for_tool_calls",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "always-send-max-tokens",
		resolved_key:  "always_send_max_tokens",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "antigravity-claude-tool-mode",
		resolved_key:  "antigravity_claude_tool_mode",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Google],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "antigravity-usage-label",
		resolved_key:  "antigravity_usage_label",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Google],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "apply-patch-tool-type",
		resolved_key:  "applyPatchToolType",
		set:           AxisSet::Catalog,
		shape:         AxisShape::Scalar,
		records:       &[],
		values:        &["freeform", "function"],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "cache-control-format",
		resolved_key:  "cache_control_format",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &["anthropic"],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "cca-legacy-parameters-schema",
		resolved_key:  "cca_legacy_parameters_schema",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Google],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "clamp-output-to-model-max",
		resolved_key:  "clamp_output_to_model_max",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "claude-thinking-beta-header",
		resolved_key:  "claude_thinking_beta_header",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Google],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "context-promotion-target",
		resolved_key:  "contextPromotionTarget",
		set:           AxisSet::Catalog,
		shape:         AxisShape::Scalar,
		records:       &[],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "context-window-floor",
		resolved_key:  "contextWindowFloor",
		set:           AxisSet::Catalog,
		shape:         AxisShape::Scalar,
		records:       &[],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "cost-patch",
		resolved_key:  "costPatch",
		set:           AxisSet::Catalog,
		shape:         AxisShape::Object,
		records:       &[],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "disable-adaptive-thinking",
		resolved_key:  "disable_adaptive_thinking",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Anthropic],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "disable-reasoning-on-forced-tool-choice",
		resolved_key:  "disable_reasoning_on_forced_tool_choice",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "disable-reasoning-on-tool-choice",
		resolved_key:  "disable_reasoning_on_tool_choice",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "disable-strict-tools",
		resolved_key:  "disable_strict_tools",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Anthropic],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "drop-thinking-when-reasoning-effort",
		resolved_key:  "drop_thinking_when_reasoning_effort",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "drop-unsigned-thinking",
		resolved_key:  "drop_unsigned_thinking",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Google],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "edit-revision",
		resolved_key:  "editRevision",
		set:           AxisSet::Catalog,
		shape:         AxisShape::Scalar,
		records:       &[],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "empty-length-finish-is-context-error",
		resolved_key:  "empty_length_finish_is_context_error",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "escape-builtin-tool-names",
		resolved_key:  "escape_builtin_tool_names",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Anthropic],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "extra-body",
		resolved_key:  "extra_body",
		set:           AxisSet::Wire,
		shape:         AxisShape::Object,
		records:       &[CompatRecord::OpenAi],
		values:        &[],
		verbatim_keys: true,
	},
	AxisDef {
		key:           "filter-reasoning-history",
		resolved_key:  "filter_reasoning_history",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "flash-stream-leak-workaround",
		resolved_key:  "flash_stream_leak_workaround",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Google],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "harmony-leak-mitigation",
		resolved_key:  "harmony_leak_mitigation",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "include-encrypted-reasoning",
		resolved_key:  "include_encrypted_reasoning",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "inject-claude-code-instruction",
		resolved_key:  "inject_claude_code_instruction",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Anthropic],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "input-modalities",
		resolved_key:  "inputModalities",
		set:           AxisSet::Catalog,
		shape:         AxisShape::Array,
		records:       &[],
		values:        &["text", "image"],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "kimi-api-format",
		resolved_key:  "kimi_api_format",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi],
		values:        &["openai", "anthropic"],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "limits-patch",
		resolved_key:  "limitsPatch",
		set:           AxisSet::Catalog,
		shape:         AxisShape::Object,
		records:       &[],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "long-context-cost",
		resolved_key:  "longContext",
		set:           AxisSet::Catalog,
		shape:         AxisShape::Object,
		records:       &[],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "long-usage-limit-fallback",
		resolved_key:  "longUsageLimitFallback",
		set:           AxisSet::Catalog,
		shape:         AxisShape::Scalar,
		records:       &[],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "max-tokens-field",
		resolved_key:  "max_tokens_field",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi],
		values:        &["max_completion_tokens", "max_tokens"],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "model-router",
		resolved_key:  "model_router",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Devin],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "multimodal-function-response",
		resolved_key:  "multimodal_function_response",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Google],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "native-kimi-k3-reasoning",
		resolved_key:  "native_kimi_k3_reasoning",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "official-endpoint",
		resolved_key:  "official_endpoint",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Anthropic, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "omit-reasoning-effort",
		resolved_key:  "omit_reasoning_effort",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "priority",
		resolved_key:  "priority",
		set:           AxisSet::Catalog,
		shape:         AxisShape::Scalar,
		records:       &[],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "prompt-cache-breakpoint-ttl",
		resolved_key:  "prompt_cache_breakpoint_ttl",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &["30m"],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "prompt-cache-maximum-checkpoints",
		resolved_key:  "prompt_cache_maximum_checkpoints",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Bedrock],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "prompt-cache-minimum-tokens",
		resolved_key:  "prompt_cache_minimum_tokens",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Bedrock],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "prompt-cache-mode",
		resolved_key:  "prompt_cache_mode",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Bedrock],
		values:        &["none", "automatic", "explicit"],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "prompt-cache-session-header",
		resolved_key:  "prompt_cache_session_header",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &["x-grok-conv-id"],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "qwen-preserve-thinking",
		resolved_key:  "qwen_preserve_thinking",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "reasoning-content-field",
		resolved_key:  "reasoning_content_field",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &["reasoning_content", "reasoning", "reasoning_text"],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "reasoning-deltas-may-be-cumulative",
		resolved_key:  "reasoning_deltas_may_be_cumulative",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "reasoning-disable-mode",
		resolved_key:  "reasoning_disable_mode",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[
			"omit",
			"lowest-effort",
			"none-effort",
			"openrouter-enabled-false",
			"cline-enabled-false",
			"venice-disable-thinking",
			"zai-thinking-disabled",
			"qwen-enable-thinking-false",
			"qwen-template-false",
			"chat-template-thinking-false",
		],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "reasoning-effort-map",
		resolved_key:  "reasoning_effort_map",
		set:           AxisSet::Wire,
		shape:         AxisShape::Object,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "reject-root-object-union",
		resolved_key:  "reject_root_object_union",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "replay-reasoning-content",
		resolved_key:  "replay_reasoning_content",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "replay-unsigned-thinking",
		resolved_key:  "replay_unsigned_thinking",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Anthropic],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "requires-assistant-after-tool-result",
		resolved_key:  "requires_assistant_after_tool_result",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "requires-assistant-content-for-tool-calls",
		resolved_key:  "requires_assistant_content_for_tool_calls",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "requires-cursor-tool-schema-projection",
		resolved_key:  "requiresCursorToolSchemaProjection",
		set:           AxisSet::Catalog,
		shape:         AxisShape::Scalar,
		records:       &[],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "requires-mistral-tool-ids",
		resolved_key:  "requires_mistral_tool_ids",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "requires-reasoning-content-for-all-assistant-turns",
		resolved_key:  "requires_reasoning_content_for_all_assistant_turns",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "requires-reasoning-content-for-tool-calls",
		resolved_key:  "requires_reasoning_content_for_tool_calls",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "requires-reasoning-off-juice-instruction",
		resolved_key:  "requires_reasoning_off_juice_instruction",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "requires-skip-thought-signature",
		resolved_key:  "requires_skip_thought_signature",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Google],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "requires-skip-thought-signature-on-first-function-call",
		resolved_key:  "requires_skip_thought_signature_on_first_function_call",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Google],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "requires-thinking-as-text",
		resolved_key:  "requires_thinking_as_text",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "requires-thinking-enabled",
		resolved_key:  "requires_thinking_enabled",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Anthropic],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "requires-tool-result-id",
		resolved_key:  "requires_tool_result_id",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Anthropic],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "requires-tool-result-name",
		resolved_key:  "requires_tool_result_name",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "retry-without-strict-on-grammar-error",
		resolved_key:  "retry_without_strict_on_grammar_error",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "service-tier-cost",
		resolved_key:  "serviceTierCost",
		set:           AxisSet::Catalog,
		shape:         AxisShape::Object,
		records:       &[],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "signing-endpoint",
		resolved_key:  "signing_endpoint",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Anthropic],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "stream-first-event-timeout-ms",
		resolved_key:  "stream_first_event_timeout_ms",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses, CompatRecord::Google],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "stream-idle-timeout-ms",
		resolved_key:  "stream_idle_timeout_ms",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[
			CompatRecord::OpenAi,
			CompatRecord::OpenAiResponses,
			CompatRecord::Anthropic,
			CompatRecord::Bedrock,
			CompatRecord::Google,
		],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "stream-markup-healing-pattern",
		resolved_key:  "stream_markup_healing_pattern",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &["kimi", "dsml", "qwen", "thinking", "harmony"],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "strict-responses-pairing",
		resolved_key:  "strict_responses_pairing",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "strip-deepseek-special-tokens",
		resolved_key:  "strip_deepseek_special_tokens",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "strip-image-input",
		resolved_key:  "strip_image_input",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[
			CompatRecord::OpenAi,
			CompatRecord::OpenAiResponses,
			CompatRecord::Anthropic,
			CompatRecord::Google,
		],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-all-turns-reasoning-context",
		resolved_key:  "supports_all_turns_reasoning_context",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-context-management",
		resolved_key:  "supports_context_management",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Anthropic],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-developer-role",
		resolved_key:  "supports_developer_role",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-eager-tool-input-streaming",
		resolved_key:  "supports_eager_tool_input_streaming",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Anthropic],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-forced-tool-choice",
		resolved_key:  "supports_forced_tool_choice",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[
			CompatRecord::OpenAi,
			CompatRecord::OpenAiResponses,
			CompatRecord::Anthropic,
		],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-function-part-id",
		resolved_key:  "supports_function_part_id",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Google],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-image-detail-original",
		resolved_key:  "supports_image_detail_original",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-long-cache-retention",
		resolved_key:  "supports_long_cache_retention",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Anthropic],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-long-prompt-cache-retention",
		resolved_key:  "supports_long_prompt_cache_retention",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses, CompatRecord::Bedrock],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-mid-conversation-system",
		resolved_key:  "supports_mid_conversation_system",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Anthropic],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-mid-conversation-tool-changes",
		resolved_key:  "supports_mid_conversation_tool_changes",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Anthropic],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-multiple-system-messages",
		resolved_key:  "supports_multiple_system_messages",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-named-tool-choice",
		resolved_key:  "supports_named_tool_choice",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-obfuscation-opt-out",
		resolved_key:  "supports_obfuscation_opt_out",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-output-effort",
		resolved_key:  "supports_output_effort",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Anthropic],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-parallel-tool-calls",
		resolved_key:  "supports_parallel_tool_calls",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Devin],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-penalty-and-stop-params",
		resolved_key:  "supports_penalty_and_stop_params",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-per-message-effort",
		resolved_key:  "supports_per_message_effort",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Anthropic],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-prompt-cache-breakpoints",
		resolved_key:  "supports_prompt_cache_breakpoints",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-prompt-cache-key",
		resolved_key:  "supports_prompt_cache_key",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-reasoning-effort",
		resolved_key:  "supports_reasoning_effort",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-reasoning-params",
		resolved_key:  "supports_reasoning_params",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-reasoning-summary",
		resolved_key:  "supports_reasoning_summary",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-sampling-params",
		resolved_key:  "supports_sampling_params",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[
			CompatRecord::OpenAi,
			CompatRecord::OpenAiResponses,
			CompatRecord::Anthropic,
		],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-store",
		resolved_key:  "supports_store",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-strict-mode",
		resolved_key:  "supports_strict_mode",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-thinking-binding-controls",
		resolved_key:  "supports_thinking_binding_controls",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Anthropic],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-tool-choice",
		resolved_key:  "supports_tool_choice",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-turn-scoped-system",
		resolved_key:  "supports_turn_scoped_system",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Anthropic],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "supports-usage-in-streaming",
		resolved_key:  "supports_usage_in_streaming",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "template-reasoning-effort",
		resolved_key:  "qwen_template_reasoning_effort",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "thinking-default-level",
		resolved_key:  "defaultLevel",
		set:           AxisSet::Thinking,
		shape:         AxisShape::Scalar,
		records:       &[],
		values:        &["minimal", "low", "medium", "high", "xhigh", "max"],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "thinking-effort-budgets",
		resolved_key:  "effortBudgets",
		set:           AxisSet::Thinking,
		shape:         AxisShape::Object,
		records:       &[],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "thinking-effort-map",
		resolved_key:  "effortMap",
		set:           AxisSet::Thinking,
		shape:         AxisShape::Object,
		records:       &[],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "thinking-efforts",
		resolved_key:  "efforts",
		set:           AxisSet::Thinking,
		shape:         AxisShape::Array,
		records:       &[],
		values:        &["minimal", "low", "medium", "high", "xhigh", "max"],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "thinking-format",
		resolved_key:  "thinking_format",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[
			"openai",
			"openrouter",
			"zai",
			"kimi",
			"qwen",
			"qwen-chat-template",
			"chat-template",
		],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "thinking-keep",
		resolved_key:  "thinking_keep",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "thinking-loop-guard",
		resolved_key:  "thinking_loop_guard",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[
			CompatRecord::OpenAi,
			CompatRecord::OpenAiResponses,
			CompatRecord::Anthropic,
			CompatRecord::Google,
		],
		values:        &["gemini", "deepseek", "xai"],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "thinking-mode",
		resolved_key:  "mode",
		set:           AxisSet::Thinking,
		shape:         AxisShape::Scalar,
		records:       &[],
		values:        &[
			"effort",
			"budget",
			"google-level",
			"anthropic-adaptive",
			"anthropic-budget-effort",
		],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "thinking-prefix-binding",
		resolved_key:  "prefixBinding",
		set:           AxisSet::Thinking,
		shape:         AxisShape::Scalar,
		records:       &[],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "thinking-requires-effort",
		resolved_key:  "requiresEffort",
		set:           AxisSet::Thinking,
		shape:         AxisShape::Scalar,
		records:       &[],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "thinking-supports-display",
		resolved_key:  "supportsDisplay",
		set:           AxisSet::Thinking,
		shape:         AxisShape::Scalar,
		records:       &[],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "thinking-suppress-when-off",
		resolved_key:  "suppressWhenOff",
		set:           AxisSet::Thinking,
		shape:         AxisShape::Scalar,
		records:       &[],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "tool-schema-flavor",
		resolved_key:  "tool_schema_flavor",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &["moonshot-mfjs", "grammar", "none"],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "tool-strict-mode",
		resolved_key:  "tool_strict_mode",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi],
		values:        &["all_strict", "none", "mixed"],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "trust-explicit-thinking-only",
		resolved_key:  "trust_explicit_thinking_only",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::Devin],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "uses-openai-tool-call-id-limit",
		resolved_key:  "uses_openai_tool_call_id_limit",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "when-thinking",
		resolved_key:  "when_thinking",
		set:           AxisSet::Wire,
		shape:         AxisShape::Object,
		records:       &[CompatRecord::OpenAi],
		values:        &[],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "wire-model-id-mode",
		resolved_key:  "wire_model_id_mode",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi, CompatRecord::OpenAiResponses],
		values:        &["raw", "cline-pass", "firepass", "fireworks", "openrouter"],
		verbatim_keys: false,
	},
	AxisDef {
		key:           "zai-reasoning-effort-dialect",
		resolved_key:  "zai_reasoning_effort_dialect",
		set:           AxisSet::Wire,
		shape:         AxisShape::Scalar,
		records:       &[CompatRecord::OpenAi],
		values:        &[],
		verbatim_keys: false,
	},
];

/// Finds a compatibility axis by its kebab-case directive spelling.
#[must_use]
pub fn axis(key: &str) -> Option<&'static AxisDef> {
	AXES
		.binary_search_by_key(&key, |definition| definition.key)
		.ok()
		.map(|index| &AXES[index])
}
