//! Persistence: render live state as a replayable diff-from-default script.
//!
//! Persistence is not a serializer. [`Ctx::dump`] emits the minimal command
//! script that reconstructs the archived subset of current state when
//! executed on a context in default state: reset preambles for binds and
//! aliases (whole-table state), then one `name value` line per variable
//! diverging from its default. Aliases are state here, not runtime debris —
//! the Source-lineage split between machine-written `config.cfg` and
//! hand-written `autoexec.cfg` exists *because* aliases didn't persist;
//! this design removes the reason for that split.

use std::fmt::Write as _;

use omp_core::{Str, StrMut};

use crate::{Ctx, RegItem, VarFlags, value::write_atom};

/// Current generated `config.cfg` schema.
pub const CFG_SCHEMA_VERSION: u32 = 1;
/// Stable prefix identifying generated cfg files.
pub const CFG_HEADER_PREFIX: &str = "// generated by omp-con dump;";

/// Scope options for [`Ctx::dump`].
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct DumpOptions {
	/// Include vars without the `ARCHIVE` flag.
	pub all_vars:                  bool,
	/// Include vars still at their default (full snapshot instead of diff).
	pub include_defaults:          bool,
	/// Include registration-default values when the archive layer contains an
	/// explicit write for that variable.
	pub include_archived_defaults: bool,
	/// Include registration-default values when the session layer contains an
	/// explicit write. Used by `writecfg` after an interactive convar command.
	pub include_session_defaults:  bool,
}

impl Ctx {
	/// Renders the persistence script; see the module docs for semantics.
	///
	/// D10: the default behavior emits only archived values that differ from
	/// their registration-time defaults.
	///
	/// Output is deterministic: binds, aliases, and vars each sorted by
	/// name. Replaying via [`Ctx::exec`] restores the captured state.
	#[must_use]
	pub fn dump(&self) -> Str {
		self.dump_with_options(DumpOptions::default())
	}

	/// Renders a persistence script with explicit scope options.
	#[must_use]
	pub fn dump_with_options(&self, options: DumpOptions) -> Str {
		let mut out = StrMut::new("");
		out.push_str("// generated by omp-con dump; schema=1; replay with `exec`\n");

		// Binds: a diff against the sealed default bind cfg when one ran
		// (ADR 0014: defaults are a cfg, so persistence records only the
		// user's divergence); otherwise the whole table behind a reset.
		let bind_line = |out: &mut StrMut, key: &str, script: &str| {
			out.push_str("bind ");
			let _ = write_atom(out, key);
			out.push(' ');
			let _ = write_atom(out, script);
			out.push('\n');
		};
		if let Some((removed, changed)) = self.bind_diff() {
			for key in removed {
				out.push_str("unbind ");
				let _ = write_atom(&mut out, key.as_str());
				out.push('\n');
			}
			for (key, script) in changed {
				bind_line(&mut out, key.as_str(), script.as_str());
			}
		} else {
			out.push_str("unbindall\n");
			for (key, script) in self.binds() {
				bind_line(&mut out, key.as_str(), script.as_str());
			}
		}

		out.push_str("unaliasall\n");
		for (name, body) in self.aliases() {
			out.push_str("alias ");
			let _ = write_atom(&mut out, name.as_str());
			out.push(' ');
			let _ = write_atom(&mut out, body.as_str());
			out.push('\n');
		}

		let mut vars: Vec<_> = (0..self.item_count())
			.filter_map(|idx| match self.item_at(idx) {
				Some((RegItem::Var(spec), state)) => Some((spec, state)),
				_ => None,
			})
			.collect();
		vars.sort_unstable_by_key(|(spec, _)| spec.name);
		for (spec, state) in vars {
			if !options.all_vars && !spec.flags.contains(VarFlags::ARCHIVE) {
				continue;
			}
			let value = state.value();
			if !options.include_defaults
				&& value == *state.default_value()
				&& !(options.include_archived_defaults && self.has_archive_write(spec.name))
				&& !(options.include_session_defaults && self.has_session_write(spec.name))
			{
				continue;
			}
			let _ = writeln!(out, "{} {value}", spec.name);
		}
		let mut dynamic: Vec<_> = self.dynamic_vars_for_dump().collect();
		dynamic.sort_unstable_by(|left, right| left.0.cmp(right.0));
		for (name, flags, default, value) in dynamic {
			if !options.all_vars && !flags.contains(VarFlags::ARCHIVE) {
				continue;
			}
			if !options.include_defaults
				&& value == default
				&& !(options.include_archived_defaults && self.has_archive_write(name))
				&& !(options.include_session_defaults && self.has_session_write(name))
			{
				continue;
			}
			let _ = writeln!(out, "{name} {value}");
		}
		out.freeze()
	}
}
