#!/usr/bin/env python3
"""Render cargo-about JSON deterministically, retaining the source-notice prelude."""
import argparse
import difflib
import itertools
import json
from pathlib import Path

# Enough context to see which crate/license drifted without flooding CI logs.
DIFF_LINES = 400

MARKER = "RUST DEPENDENCY LICENSES\n=========================\n"


def render(data: dict) -> str:
    groups = {}
    for license in data["licenses"]:
        key = (license["id"], license["name"], "\n".join(line.rstrip() for line in license["text"].splitlines()).strip())
        users = groups.setdefault(key, set())
        for entry in license["used_by"]:
            crate = entry["crate"]
            users.add((crate["name"], crate["version"], crate.get("repository") or ""))
    if not groups:
        raise ValueError("cargo-about returned no license texts")
    parts = [MARKER, "\nGenerated by cargo-about 0.8.2 with workspace, all-feature, all-target,\n"
             "build and development dependencies, using offline license discovery.\n"
             "Regenerate with just license-notices-update; verify with just license-check.\n"]
    for (_, name, text), users in sorted(groups.items()):
        parts.append("\n" + "-" * 79 + f"\nLicense: {name}\n\nUsed by:\n")
        for name, version, repository in sorted(users):
            suffix = f" ({repository})" if repository else ""
            parts.append(f"- {name} {version}{suffix}\n")
        parts.append("\n" + text + "\n")
    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("data", type=Path)
    parser.add_argument("notices", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    original = args.notices.read_text()
    if original.count(MARKER) != 1:
        parser.error("notices must contain exactly one Rust dependency section marker")
    expected = original.split(MARKER)[0] + render(json.loads(args.data.read_text()))
    if args.check:
        if original != expected:
            print("Rust dependency notices are stale; run just license-notices-update")
            diff = difflib.unified_diff(
                original.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=str(args.notices),
                tofile=f"{args.notices} (expected)",
            )
            print("".join(itertools.islice(diff, DIFF_LINES)), end="")
            return 1
        print("Rust dependency notices match the locked cargo-about inventory and license texts")
        return 0
    args.notices.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
